/**
 * Exports the question bank, findings library, industries, modules, and
 * niches as JSON so the Excel workbook (and any Copilot agent) is always
 * generated from the code, never maintained by hand.
 */
import { writeFileSync } from "node:fs";
import { QUESTIONS } from "../src/lib/diagnostic/questions";
import { FINDING_RULES } from "../src/lib/diagnostic/findings";
import { INDUSTRIES } from "../src/lib/diagnostic/industries";
import { CATEGORY_LABELS } from "../src/lib/diagnostic/labels";
import { MODULES } from "../src/lib/diagnostic/modules";
import { NICHES } from "../src/lib/diagnostic/niches";
import { CATEGORY_IDS } from "../src/lib/diagnostic/types";

const out = {
  generatedAt: new Date().toISOString(),
  categories: CATEGORY_IDS.map((id) => ({ id, ...CATEGORY_LABELS[id] })),
  industries: Object.values(INDUSTRIES),
  questions: QUESTIONS,
  findings: FINDING_RULES.map((rule) => {
    const { when, ...rest } = rule;
    void when; // trigger logic stays in code; only data is exported
    return rest;
  }),
  modules: Object.values(MODULES),
  niches: NICHES,
};
const path = process.argv[2] ?? "docs/question-bank.json";
writeFileSync(path, JSON.stringify(out, null, 2));
console.log(`wrote ${path}`);

// SQL seed for reporting.questions (see supabase/migrations/0002_reporting_schema.sql)
const esc = (v: string | null | undefined) => (v === null || v === undefined ? "null" : `'${String(v).replace(/'/g, "''")}'`);
const VERSION = "1";
const rows = QUESTIONS.map(
  (q) =>
    `(${esc(q.id)}, ${esc(VERSION)}, ${esc(q.category)}, ${esc(q.topic)}, ${esc(q.prompt)}, ${esc(q.branch ?? null)}, ${q.weights.logistics_3pl}, ${q.weights.light_manufacturing}, ${q.weights.other}, ${q.critical ? "true" : "false"}, ${q.critical ? q.critical.atOrBelow : "null"})`,
);
const sql = [
  "-- Generated by scripts/export-bank.mts. Do not edit by hand.",
  "insert into reporting.questions (id, version, category, topic, prompt, industry_rule, weight_logistics_3pl, weight_light_manufacturing, weight_other, critical_flag, critical_at_or_below) values",
  rows.join(",\n"),
  "on conflict (id, version) do update set category = excluded.category, topic = excluded.topic, prompt = excluded.prompt, industry_rule = excluded.industry_rule, weight_logistics_3pl = excluded.weight_logistics_3pl, weight_light_manufacturing = excluded.weight_light_manufacturing, weight_other = excluded.weight_other, critical_flag = excluded.critical_flag, critical_at_or_below = excluded.critical_at_or_below;",
  "",
].join("\n");
writeFileSync("supabase/seed/questions.sql", sql);
console.log("wrote supabase/seed/questions.sql");
