-- Reporting schema
--
-- The product plan specifies a normalized data model:
--   organizations, contacts, assessments, answers, questions, scores,
--   findings, enrichments, leads, events
-- The operational store keeps assessments as documents (JSONB) for speed of
-- change during the MVP. This migration exposes the plan's model as views in
-- a `reporting` schema so analysts, Copilot agents, and BI tools can query
-- the plan's shapes without the app being rewritten. `questions` is a real
-- table seeded from the code (see supabase/seed/questions.sql, generated by
-- `npm run docs:bank`).

create schema if not exists reporting;

-- ---------------------------------------------------------------- questions (reference data, versioned)
create table if not exists reporting.questions (
  id            text not null,
  version       text not null,
  category      text not null,
  topic         text not null,
  prompt        text not null,
  industry_rule text,              -- branch trigger, if any
  weight_logistics_3pl int not null,
  weight_light_manufacturing int not null,
  weight_other  int not null,
  critical_flag boolean not null default false,
  critical_at_or_below int,
  primary key (id, version)
);

-- ---------------------------------------------------------------- organizations
create or replace view reporting.organizations as
select
  a.id                                   as id,          -- one organization row per assessment (no dedup in MVP)
  a.profile->>'companyName'              as name,
  coalesce(a.enrichment->>'domain', a.profile->>'website') as domain,
  a.profile->>'industry'                 as industry,
  a.enrichment->'naics'                  as naics,
  jsonb_build_object('zip', a.profile->>'zip', 'territory', a.enrichment->>'territoryLabel') as address,
  jsonb_build_object('employees', a.profile->>'employeeBand', 'revenue', a.profile->>'revenueBand') as size_band,
  a.profile->>'niche'                    as niche
from public.assessments a;

-- ---------------------------------------------------------------- contacts
create or replace view reporting.contacts as
select
  l.id                 as id,
  l.assessment_id      as organization_id,
  l.name,
  l.role               as title,
  l.email,
  l.phone,
  jsonb_build_object('report', l.consent_report, 'marketing', l.consent_marketing, 'at', l.consent_at, 'version', l.consent_text_version) as consent
from public.leads l;

-- ---------------------------------------------------------------- assessments
create or replace view reporting.assessments as
select
  a.id,
  a.id                              as organization_id,
  l.id                              as contact_id,
  '1'                               as version,
  a.status,
  a.created_at                      as started_at,
  a.completed_at,
  a.attribution->>'module'          as entry_module,
  a.attribution->>'partnerCode'     as partner_code
from public.assessments a
left join public.leads l on l.assessment_id = a.id;

-- ---------------------------------------------------------------- answers
create or replace view reporting.answers as
select
  a.id || ':' || kv.key             as id,
  a.id                              as assessment_id,
  kv.key                            as question_id,
  case when jsonb_typeof(kv.value) = 'number' then (kv.value)::text::numeric end as answer_value,
  case when jsonb_typeof(kv.value) = 'string' then kv.value #>> '{}' end          as answer_text
from public.assessments a
cross join lateral jsonb_each(coalesce(a.answers, '{}'::jsonb)) as kv(key, value);

-- ---------------------------------------------------------------- scores
create or replace view reporting.scores as
select
  a.id || ':' || (c->>'category')   as id,
  a.id                              as assessment_id,
  c->>'category'                    as category,
  (c->>'score')::numeric            as raw_score,
  (a.result->'scores'->>'confidence')::numeric as confidence,
  c->>'band'                        as band
from public.assessments a
cross join lateral jsonb_array_elements(coalesce(a.result->'scores'->'categories', '[]'::jsonb)) as c
union all
select
  a.id || ':overall',
  a.id,
  'overall',
  (a.result->'scores'->>'overall')::numeric,
  (a.result->'scores'->>'confidence')::numeric,
  a.result->'scores'->>'overallBand'
from public.assessments a
where a.result is not null;

-- ---------------------------------------------------------------- findings
create or replace view reporting.findings as
select
  a.id || ':' || (f->>'id')         as id,
  a.id                              as assessment_id,
  f->>'id'                          as finding_code,
  case f->>'kind' when 'strength' then 'strength' else 'investigate' end as severity,
  f->>'body'                        as rationale,
  f->>'title'                       as approved_copy,
  f->>'detail'                      as approved_detail,
  (f->'questionIds')                as question_ids
from public.assessments a
cross join lateral jsonb_array_elements(coalesce(a.result->'findings', '[]'::jsonb) || coalesce(a.result->'strengths', '[]'::jsonb)) as f
union all
select
  a.id || ':flag:' || (f->>'questionId'),
  a.id,
  'critical_flag',
  'critical',
  f->>'message',
  f->>'message',
  null,
  jsonb_build_array(f->>'questionId')
from public.assessments a
cross join lateral jsonb_array_elements(coalesce(a.result->'scores'->'criticalFlags', '[]'::jsonb)) as f;

-- ---------------------------------------------------------------- enrichments
create or replace view reporting.enrichments as
select
  a.id || ':' || (s.ordinality)::text as id,
  a.id                              as organization_id,
  s.value->>'source'                as source,
  s.value->>'sourceUrl'             as source_url,
  s.value                           as payload,
  (a.enrichment->>'computedAt')::timestamptz as matched_at,
  null::numeric                     as confidence   -- matches are name/location based; no numeric confidence in MVP
from public.assessments a
cross join lateral jsonb_array_elements(coalesce(a.enrichment->'signals', '[]'::jsonb)) with ordinality as s(value, ordinality);

-- ---------------------------------------------------------------- leads
create or replace view reporting.leads as
select
  l.id,
  l.assessment_id,
  (l.lead_score->>'total')::int     as quality_score,
  l.lead_score->>'tier'             as quality_tier,
  (a.profile->>'renewalMonth')::int as renewal_month,
  a.profile->>'incumbentTenure'     as broker,          -- incumbent tenure band; broker name is not collected
  a.profile->>'premiumBand'         as premium_band,
  l.follow_up_owner                 as owner,
  l.disposition                     as stage,
  l.workshop_requested,
  l.licensed_review_completed,
  l.created_at
from public.leads l
join public.assessments a on a.id = l.assessment_id;

-- ---------------------------------------------------------------- events
create or replace view reporting.events as
select
  e.id,
  e.assessment_id,
  e.name                            as event_name,
  a.attribution->>'campaign'        as campaign,
  a.attribution->>'partnerCode'     as partner_code,
  a.attribution->>'module'          as entry_module,
  e.properties,
  e.created_at
from public.events e
left join public.assessments a on a.id = e.assessment_id;

-- ---------------------------------------------------------------- access
-- Producers (via RLS on the base tables) and the service role can read the
-- views. Grant read to authenticated; RLS on public.* still applies.
grant usage on schema reporting to authenticated, service_role;
grant select on all tables in schema reporting to authenticated, service_role;
alter default privileges in schema reporting grant select on tables to authenticated, service_role;
